name: my_quotes
description: Mobile app for storing personal quotes

version: 1.0.1+101

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: 3.0.0+1
  get_it: 1.0.3+2
  rxdart: ^0.22.1+1
  sqflite: ^1.1.6+3
  path_provider: ^1.2.0
  share: 0.6.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/icons/icomoon.ttf
