name: my_quotes
description: Mobile app for storing personal quotes

version: 1.2.1+121

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: 4.0.4
  get_it: 4.0.0
  rxdart: 0.23.1
  sqflite: 1.2.1
  path_provider: 1.6.1
  share: 0.6.3+6
  url_launcher: 5.4.2

dev_dependencies:
  pedantic: 1.9.0

flutter:
  uses-material-design: true

  fonts:
    - family: icomoon
      fonts:
        - asset: assets/icons/icomoon.ttf
